In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.1.0'

In [3]:
#딥러닝 구동에 필요한 케라스함수
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

#라이브러리
import numpy as np
import tensorflow as tf

In [4]:
#랜덤 정해놓기
np.random.seed(3)
tf.random.set_seed(3)

In [12]:
Data_set = np.loadtxt('C:/Users/gram/Documents/GitHub/AI-NLP/ThoraricSurgery.csv',delimiter=',')

# 환자 기록과 수술결과를 X, Y로 나누기
X = Data_set[:, 0:17]
Y = Data_set[:, 17]

In [15]:
#딥러닝 구조를 결정합니다(모델을 설정하고 실행하는 부분입니다)
model=Sequential()
model.add(Dense(30,input_dim=17,activation='relu'))
model.add(Dense(1,activation='sigmoid'))

#딥러닝을 실행합니다.
model.compile(loss='mean_squared_error',optimizer='adam',metrics=['accuracy'])
model.fit(X,Y,epochs=100,batch_size=10)

Train on 470 samples
Epoch 1/100
470/470 [==============================] - 1s 2ms/sample - loss: 0.1496 - accuracy: 0.8383
Epoch 2/100
470/470 [==============================] - 0s 187us/sample - loss: 0.1445 - accuracy: 0.8447
Epoch 3/100
470/470 [==============================] - 0s 185us/sample - loss: 0.1450 - accuracy: 0.8511
Epoch 4/100
470/470 [==============================] - 0s 199us/sample - loss: 0.1442 - accuracy: 0.8511 - loss: 0.1589 - accuracy: 0.83
Epoch 5/100
470/470 [==============================] - 0s 212us/sample - loss: 0.1449 - accuracy: 0.8511
Epoch 6/100
470/470 [==============================] - 0s 255us/sample - loss: 0.1440 - accuracy: 0.8511
Epoch 7/100
470/470 [==============================] - 0s 263us/sample - loss: 0.1459 - accuracy: 0.8468
Epoch 8/100
470/470 [==============================] - 0s 238us/sample - loss: 0.1470 - accuracy: 0.8511
Epoch 9/100
470/470 [==============================] - 0s 187us/sample - loss: 0.1438 - accuracy: 0.8511
Epoc

470/470 [==============================] - 0s 297us/sample - loss: 0.1311 - accuracy: 0.8574
Epoch 78/100
470/470 [==============================] - 0s 325us/sample - loss: 0.1246 - accuracy: 0.8553
Epoch 79/100
470/470 [==============================] - 0s 318us/sample - loss: 0.1220 - accuracy: 0.8489
Epoch 80/100
470/470 [==============================] - 0s 291us/sample - loss: 0.1382 - accuracy: 0.8511
Epoch 81/100
470/470 [==============================] - 0s 269us/sample - loss: 0.1334 - accuracy: 0.8553
Epoch 82/100
470/470 [==============================] - 0s 206us/sample - loss: 0.1215 - accuracy: 0.8489
Epoch 83/100
470/470 [==============================] - 0s 197us/sample - loss: 0.1251 - accuracy: 0.8596
Epoch 84/100
470/470 [==============================] - 0s 168us/sample - loss: 0.1232 - accuracy: 0.8489
Epoch 85/100
470/470 [==============================] - 0s 178us/sample - loss: 0.1254 - accuracy: 0.8596
Epoch 86/100
470/470 [==============================] - 0s 

In [16]:
#결과 출력
print('\n Accuracy:%.4f'%(model.evaluate(X,Y)[1]))

470/470 [==============================] - 0s 59us/sample - loss: 0.1213 - accuracy: 0.8574

 Accuracy:0.8574


In [17]:
import numpy as np

In [18]:
d=np.array([[[1,2,3,4],
            [5,6,7,8],
            [9,10,11,12]],
           [1,2,3,4],
           [5,6,7,8]])

c:\users\gram\anaconda3\envs\tf_env\lib\site-packages\ipykernel_launcher.py:5: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  """


In [19]:
d

array([list([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]),
       list([1, 2, 3, 4]), list([5, 6, 7, 8])], dtype=object)

In [20]:
len(d)

3

In [21]:
d=np.zeros(5,dtype='U4')
d

array(['', '', '', '', ''], dtype='<U4')

In [22]:
d[0]='abc'
d[1]='abcd'
d[2]='ABC'
d

array(['abc', 'abcd', 'ABC', '', ''], dtype='<U4')

In [23]:
e=np.ones((2,3,4),dtype='i8')
e

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int64)

In [24]:
b=np.zeros((2,3))
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [25]:
f=np.ones_like(b,dtype='f')
f

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [26]:
g=np.empty((4,3))
g

array([[1.27621817e-311, 3.16202013e-322, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 1.21026593e-071],
       [8.46913627e+165, 8.30135922e-067, 9.77232412e+165],
       [4.51851225e-037, 8.93341729e+165, 9.44366119e+164]])

In [27]:
A=np.array([[1,2,3],[4,5,6]])#2*3행렬
A

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
A.T#3*2행렬

array([[1, 4],
       [2, 5],
       [3, 6]])

In [29]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
a=np.arange(12)

In [35]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [34]:
a.reshape(3,-1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])